### ISSUE TITLE
Working link

### ISSUE THREAD

**Issue by NikWillmore** [smistad/GPU-Marching-Cubes#10]
Link to write up is down. I found it here instead:

https://www.eriksmistad.no/marching-cubes-implementation-using-opencl-and-opengl/

**Comment by smistad** [comment]
Where is the broken link?

**Comment by NikWillmore** [comment]
Looks fine now, sorry, but I ran into a thebigblob.com bad link last night that I found the good link to by using Archive.org on it to then search for the first sentence. Perhaps it was on another reference page. Google still thinks the bad link is here though:

https://www.google.com/search?q=linkto%3Ahttp%3A%2F%2Fwww.thebigblob.com%2Fmarching-cubes-implementation-using-opencl-and-opengl%2F&ie=utf-8&oe=utf-8
