### ISSUE TITLE
Some errors found in cl.hpp while compiling

### ISSUE THREAD

**Issue by b-z** [smistad/GPU-Marching-Cubes#9]
Hi,

I'm trying to use your code but get some errors like this:

```
Error   C2664   'void cl::vector<cl::Device,10>::push_back(const T &)': cannot convert argument 1 from 'cl_device_id' to 'const cl::Device &'   OpenCL      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include\CL\cl.hpp   898
Error   C2664   'void cl::vector<cl::Platform,10>::push_back(const T &)': cannot convert argument 1 from 'cl_platform_id' to 'const cl::Platform &' OpenCL  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include\CL\cl.hpp   898
```

http://bowei.me/img/20161205181448.png

I've tried both CUDA v7.5 and v8.0 and got same errors.

Is that a bug of your code or cl.hpp? Or should I try other CUDA version?

Thanks.

**Comment by b-z** [comment]
I've commented all the codes in openCLUtilities.cpp and openCLGLUtilities.cpp, but the errors still occur.

(my IDE is visual studio 2010 and 2015)

**Comment by b-z** [comment]
## fixed

by just replacing all `cl::vector` by `std::vector` 
and comment all `#define __NO_STD_VECTOR`

**Comment by smistad** [comment]
Great that you fixed it yourself. This code is quite old, and probably not entirely up to date with newest OpenCL. The marching cubes implementation is being further developed in the FAST framework: https://github.com/smistad/fast, here is an example: https://www.youtube.com/watch?v=Xz3txaYgtKA

**Comment by b-z** [comment]
Thanks for replying
:)
